# Generated by Django 2.1.5 on 2019-01-09 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_auto_20190108_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ratings', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publicationhouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.PublicationHouse'),
        ),
    ]
