# Generated by Django 2.1.5 on 2019-01-17 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_auto_20190116_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(default=datetime.date(2019, 1, 17), null=True),
        ),
    ]
