# Generated by Django 2.1.5 on 2019-01-14 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0005_book_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booksissued',
            field=models.ManyToManyField(to='libapp.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(default=datetime.date(2019, 1, 14), null=True),
        ),
    ]
