# Generated by Django 2.1.5 on 2019-01-15 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(default=datetime.date(2019, 1, 15), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('NE', 'Netherlands')], max_length=25, null=True),
        ),
    ]
